### ISSUE TITLE
Translation for parent/child

### ISSUE THREAD

**Issue by ozcanzaferayan** [reactjs/tr.reactjs.org#21]
Translation for parent is `ebeveyn`. But this might be confusing and not frequently used. This situation also valid for child translation.  You can vote by clicking:
For parent translation:
[![](https://api.gh-polls.com/poll/01D4J9ZWYVKNXMBZ3HQJ0SWS25/parent)](https://api.gh-polls.com/poll/01D4J9ZWYVKNXMBZ3HQJ0SWS25/parent/vote)
[![](https://api.gh-polls.com/poll/01D4J9ZWYVKNXMBZ3HQJ0SWS25/ebeveyn)](https://api.gh-polls.com/poll/01D4J9ZWYVKNXMBZ3HQJ0SWS25/ebeveyn/vote)
[![](https://api.gh-polls.com/poll/01D4J9ZWYVKNXMBZ3HQJ0SWS25/%C3%BCst)](https://api.gh-polls.com/poll/01D4J9ZWYVKNXMBZ3HQJ0SWS25/%C3%BCst/vote)
For child translation:
[![](https://api.gh-polls.com/poll/01D4J9ZYSS3D9N8N96E1G5AHXW/child)](https://api.gh-polls.com/poll/01D4J9ZYSS3D9N8N96E1G5AHXW/child/vote)
[![](https://api.gh-polls.com/poll/01D4J9ZYSS3D9N8N96E1G5AHXW/%C3%A7ocuk)](https://api.gh-polls.com/poll/01D4J9ZYSS3D9N8N96E1G5AHXW/%C3%A7ocuk/vote)
[![](https://api.gh-polls.com/poll/01D4J9ZYSS3D9N8N96E1G5AHXW/alt)](https://api.gh-polls.com/poll/01D4J9ZYSS3D9N8N96E1G5AHXW/alt/vote)

**Comment by alioguzhan** [comment]
Reminder: We also should update the [related section](https://github.com/reactjs/tr.reactjs.org/blob/master/TRANSLATION.md#ortak-%C3%A7eviriler) in TRANSLATION.md file based on this poll result.

**Comment by ozcanzaferayan** [comment]
Added parent/child translation to TRANSLATION.md based on results of this poll https://github.com/reactjs/tr.reactjs.org/pull/23
