### ISSUE TITLE
useEffect'in tercüme ikiliği

### ISSUE THREAD

**Issue by mervanyalcindag** [reactjs/tr.reactjs.org#300]
[Bir Bakışta Hook'lar](https://tr.reactjs.org/docs/hooks-overview.html) bölümünde Effect terimi orjinal haliyle bırakılmışken, [Effect Hook'unu Kullanmak](https://tr.reactjs.org/docs/hooks-effect.html) bölümünde kimi yerde **etki**
 kimi yerde de **efekt** olarak çevrilmiş. Hangi terimin kullanılması gerektiğine karar verilmesinin yararlı olacağını düşünüyorum.

**Comment by alioguzhan** [comment]
Insanlar bir sorunla karsilastiginda daha kolay yardim bulabilmesi icin hookun adini cevirmemek daha dogru olacaktir diye dusunuyorum. 

Eger bu guncellemeyi yapmak isterseniz, sizden ek olarak [TRANSLATION.md](https://github.com/reactjs/tr.reactjs.org/blob/master/TRANSLATION.md) dosyasini da uygun bir sekilde guncellemenizi rica ederim. Ki bundan sonraki arkadaslar icin referans olusturmus oluruz.
