### ISSUE TITLE
Turkish Translation Final Steps!

### ISSUE THREAD

**Issue by tesseralis** [reactjs/tr.reactjs.org#69]
Congrats on almost finishing the translation of the Turkish docs! There are just a couple more things we need to do before we can mark the core pages as complete!

* [x] Change the [DocSearch API key] #69 (https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25). One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program)
* [x] Go over the pages of the site one last time to check for consistency #88

**Comment by suyalcinkaya** [comment]
Hi there! 👋🏼
I've just signed up. I'll let you know and update it when I got it.

**Comment by suyalcinkaya** [comment]
Hi again @tesseralis.

Just got the DocSearch API key and index name and updated it. 👌🏼

**Comment by ersel** [comment]
Unsung heroes right here. Tesekkurler @suyalcinkaya @alioguzhan 🙌
